POST  http://localhost:3001/signup
Content-Type: application/json

{
    "nickname": "kakazika",
    "email": "kaka@gmail.com",
    "password": "12345"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "kaka@gmail.com",
    "password": "12345"
}

